management.endpoint.health.group.liveness.include=livenessState
demo.map.props.one.foo.bar.boo = value4
demo.map.props.one.foo.dummy = value5
demo.map.props.another.xxx.yyy = false
demo.map.props.third.prop-name.test-case.names = aaa,bbb,ccc
# completion doesn't work:
#demo.more.map.props.my-p-o-j-o.map-prop.key1.
#demo.more.map.props.myPOJO.map-prop.key2.

demo.more.map.props.str-prop=aaa
demo.more.map.props.num-prop=111

demo.more.map.props.my-p-o-j-o.map-prop.key1.map-prop.subkey1.str-prop = barbar
# not resolved in 2023.2 - and still not resolved in 2025.2
demo.more.map.props.my-p-o-j-o.text-value = fooBar
demo.more.map.props.my-p-o-j-o.num-prop = 1000
demo.more.map.props.str-pojo-map.aaa.num-prop=1
management.metrics.distribution.percentiles.http.server.requests = 1.0
management.metrics.distribution.percentiles-histogram.http.server.requests = false
# https://youtrack.jetbrains.com/issue/IDEA-389310:
# 'tasks.scheduled.execution' is a key here (slo: Map<String, ServiceLevelObjectiveBoundary[]>)
management.metrics.distribution.slo.tasks.scheduled.execution=5ms,10ms,25ms,50ms,100ms,250ms,500ms,1s,2500ms,5s,10s

## https://youtrack.jetbrains.com/issue/IDEA-194888 - answered:
spring.mvc.contentnegotiation.media-types.ustache.charset=application/activity+json

my.new.props.string-enum1-map.key1=lit1
my.new.props.string-enum1-map.key.with.dots=lit2
my.new.props.inner.string-map.key.with.dots=val2
my.new.props.inner.string-enums-map.key.with.dots=LIT3,LIT4,LIT5

