management:
  server.port: 8282
  endpoint.health.group.liveness.include: livenessState
demo:
  map:
    props:
      one:
        foo:
          foobar: value1
          foo.buzz: value2
        bar:
          dummy: value3
      another:
        key1:
          subkey1: false
          subkey2: true
      third:
        key1.key2:
          subkey1.subkey2:
            - foo
            - bar
my:
  new:
    props:
      pojo-map:
        pojo-key1:
          string-set:
            - pojo set value1_1
            - pojo set value1_2
            - pojo set value1_3
          string-map:
            key1: pojo map value1_1
            key2: pojo map value1_2
        pojo-key2:
          string-set:
            - pojo set value2_1
            - pojo set value2_2
            - pojo set value2_3
          string-map:
            key1: pojo map value2_1
            key2: pojo map value2_2
      string-list-map:
        key1:
          - value11
          - value12
          - value13
        key2:
          - value24
          - value25
